name: Send Message To Dooray CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew
    # - name: Build with Gradle
    #   run: ./gradlew build

#    curl -X POST -H "Content-Type: application/json" \
               # -d '{"key":"value"}' \
               # https://example.com/api/endpoint
               
    - name: Slack Notification
      if: always()
      run: |
        curl -X POST -H 'Content-Type: application/json' -H 'cache-control: no-cache' \
        -d '{
          {
            botName: "結果 ${{ job.status }}",
            botIconImage: "https://icons.iconarchive.com/icons/martz90/circle/256/android-icon.png",
            attachments: [{ 
              title: "CJP 「TEST」 Link",
              text: "Github Action TEST"
            }],
            title_link: $jobLink,
            text: "hogehoge"
          }
        }' \
        https://hook.dooray.com/services/1962219519412888369/2726680363655663207/6TarKP6OTbar5XLakxPZHg 


        
        # if [ '${{ job.status }}' = 'success'　]; then
        #   COLOR="good"
        # else
        #   COLOR="danger"
        # fi

        # jq -n --arg jobLink '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' --arg color "${COLOR}" '{
        #   {
        #     botName: "結果 ${{ job.status }}",
        #     botIconImage: "https://icons.iconarchive.com/icons/martz90/circle/256/android-icon.png",
        #     attachments: [{ 
        #       title: "CJP 「TEST」 Link",
        #       text: "Github Action TEST"
        #     }],
        #     title_link: $jobLink,
        #     text: "hogehoge"
        #   }
        # }' | curl ${{ secrets.SLACK_WEBHOOK_URL }} -X POST -H 'Content-Type: application/json' -H 'cache-control: no-cache' -d @-
